// LoLLM — Katalog provider bawaan.
// TIDAK ADA daftar model hardcode di sini — daftar model SELALU diambil live dari
// endpoint provider setelah API key ditambahkan (/v1/models masing-masing).
// tier: 'free' (gratis tanpa kartu kredit) | 'freemium' (kredit/kuota trial) | 'paid'
// style: 'openai' (OpenAI-compatible) | 'anthropic' (ditranslasi otomatis)

export const CATALOG = [
  {
    id: 'groq',
    name: 'Groq',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    getKey: 'https://console.groq.com/keys',
    note: 'Free tier dermawan, inferensi LPU super cepat. Tanpa kartu kredit.',
    priority: 10,
  },
  {
    id: 'github',
    name: 'GitHub Models',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://models.github.ai/inference',
    getKey: 'https://github.com/settings/tokens?type=beta',
    note: 'Gratis untuk semua akun GitHub (PAT dengan permission Models). GPT, Llama, DeepSeek, Phi.',
    priority: 12,
  },
  {
    id: 'google',
    name: 'Google AI Studio (Gemini)',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    getKey: 'https://aistudio.google.com/apikey',
    note: 'Free tier Gemini tiap menit/hari. Endpoint OpenAI-compatible resmi.',
    priority: 14,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    getKey: 'https://cloud.cerebras.ai',
    note: 'Free tier ~1jt token/hari, throughput ekstrem (wafer-scale).',
    priority: 16,
  },
  {
    id: 'zai',
    name: 'Z.AI (GLM)',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    getKey: 'https://z.ai',
    note: 'GLM-4.5-Flash & GLM-4.7-Flash benar-benar gratis (rate-limited), kuat untuk coding.',
    priority: 18,
  },
  {
    id: 'mistral',
    name: 'Mistral',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    getKey: 'https://console.mistral.ai/api-keys',
    note: 'Free tier (Experiment) di La Plateforme.',
    priority: 20,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    tier: 'freemium',
    style: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    getKey: 'https://openrouter.ai/settings/keys',
    note: 'Agregat ratusan model; banyak model gratis dengan akhiran :free.',
    priority: 22,
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    tier: 'freemium',
    style: 'openai',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    getKey: 'https://build.nvidia.com',
    note: 'Kredit trial gratis untuk semua akun NVIDIA.',
    priority: 24,
  },
  {
    id: 'huggingface',
    name: 'HuggingFace Router',
    tier: 'freemium',
    style: 'openai',
    baseUrl: 'https://router.huggingface.co/v1',
    getKey: 'https://huggingface.co/settings/tokens',
    note: 'Kredit inferensi gratis tiap bulan.',
    priority: 26,
  },
  {
    id: 'llm7',
    name: 'LLM7',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.llm7.io/v1',
    getKey: 'https://llm7.io',
    note: 'API gratis penuh, key instan tanpa kartu kredit.',
    priority: 28,
  },
  {
    id: 'pollinations',
    name: 'Pollinations',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://text.pollinations.ai/openai',
    getKey: null,
    keyless: true,
    note: 'Gratis TANPA API key — daftar modelnya pun diambil live dari endpoint.',
    extraHeaders: { Referer: 'https://github.com/NetBypass/LoLLM' },
    priority: 30,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    getKey: 'https://platform.deepseek.com/api_keys',
    note: 'Murah, kuat (deepseek-chat / deepseek-reasoner).',
    priority: 40,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    getKey: 'https://platform.openai.com/api-keys',
    note: 'Resmi OpenAI.',
    priority: 42,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    tier: 'paid',
    style: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    getKey: 'https://console.anthropic.com/settings/keys',
    note: 'Resmi Anthropic — request OpenAI ditranslasi otomatis ke Messages API.',
    priority: 44,
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    getKey: 'https://console.x.ai',
    note: 'Grok.',
    priority: 46,
  },
  {
    id: 'together',
    name: 'Together AI',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.together.xyz/v1',
    getKey: 'https://api.together.ai/settings/api-keys',
    note: 'Open-source models, kadang kredit trial.',
    priority: 48,
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.moonshot.ai/v1',
    getKey: 'https://platform.moonshot.cn/console/api-keys',
    note: 'Kimi.',
    priority: 50,
  },
];

// Provider yang langsung aktif tanpa perlu key.
export const DEFAULT_ON = ['pollinations'];

export function catalogById(id) {
  return CATALOG.find((p) => p.id === id) || null;
}
