// LoLLM — Katalog provider bawaan.
// tier: 'free' (gratis tanpa kartu kredit) | 'freemium' (kredit/kuota trial) | 'paid'
// style: 'openai' (OpenAI-compatible) | 'anthropic' (ditranslasi otomatis)

export const CATALOG = [
  {
    id: 'groq',
    name: 'Groq',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.groq.com/openai/v1',
    getKey: 'https://console.groq.com/keys',
    note: 'Free tier dermawan, inferensi LPU super cepat. Tanpa kartu kredit.',
    defaultModel: 'llama-3.3-70b-versatile',
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'openai/gpt-oss-120b', 'openai/gpt-oss-20b'],
    priority: 10,
  },
  {
    id: 'github',
    name: 'GitHub Models',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://models.github.ai/inference',
    getKey: 'https://github.com/settings/tokens?type=beta',
    note: 'Gratis untuk semua akun GitHub (PAT dengan permission Models). GPT-4o, Llama 4, DeepSeek-R1, Phi-4.',
    defaultModel: 'openai/gpt-4o-mini',
    models: ['openai/gpt-4o-mini', 'openai/gpt-4.1-mini', 'meta/Llama-4-Scout-17B-16E-Instruct', 'microsoft/Phi-4', 'deepseek/DeepSeek-R1'],
    priority: 12,
  },
  {
    id: 'google',
    name: 'Google AI Studio (Gemini)',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    getKey: 'https://aistudio.google.com/apikey',
    note: 'Free tier Gemini tiap menit/hari. Endpoint OpenAI-compatible resmi.',
    defaultModel: 'gemini-2.5-flash',
    models: ['gemini-2.5-flash', 'gemini-2.5-flash-lite', 'gemini-2.0-flash'],
    priority: 14,
  },
  {
    id: 'cerebras',
    name: 'Cerebras',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.cerebras.ai/v1',
    getKey: 'https://cloud.cerebras.ai',
    note: 'Free tier ~1jt token/hari, throughput ekstrem (wafer-scale).',
    defaultModel: 'llama-3.3-70b',
    models: ['llama-3.3-70b', 'llama3.1-8b', 'gpt-oss-120b'],
    priority: 16,
  },
  {
    id: 'zai',
    name: 'Z.AI (GLM)',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.z.ai/api/paas/v4',
    getKey: 'https://z.ai',
    note: 'GLM-4.5-Flash & GLM-4.7-Flash benar-benar gratis (rate-limited), kuat untuk coding.',
    defaultModel: 'glm-4.5-flash',
    models: ['glm-4.5-flash', 'glm-4.7-flash'],
    priority: 18,
  },
  {
    id: 'mistral',
    name: 'Mistral',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.mistral.ai/v1',
    getKey: 'https://console.mistral.ai/api-keys',
    note: 'Free tier (Experiment) di La Plateforme.',
    defaultModel: 'mistral-small-latest',
    models: ['mistral-small-latest', 'open-mistral-nemo', 'mistral-large-latest'],
    priority: 20,
  },
  {
    id: 'openrouter',
    name: 'OpenRouter',
    tier: 'freemium',
    style: 'openai',
    baseUrl: 'https://openrouter.ai/api/v1',
    getKey: 'https://openrouter.ai/settings/keys',
    note: 'Agregat ratusan model; banyak model gratis dengan akhiran :free.',
    defaultModel: 'meta-llama/llama-3.3-70b-instruct:free',
    models: ['meta-llama/llama-3.3-70b-instruct:free', 'google/gemini-2.0-flash-exp:free', 'deepseek/deepseek-chat-v3-0324:free'],
    priority: 22,
  },
  {
    id: 'nvidia',
    name: 'NVIDIA NIM',
    tier: 'freemium',
    style: 'openai',
    baseUrl: 'https://integrate.api.nvidia.com/v1',
    getKey: 'https://build.nvidia.com',
    note: 'Kredit trial gratis untuk semua akun NVIDIA.',
    defaultModel: 'meta/llama-3.3-70b-instruct',
    models: ['meta/llama-3.3-70b-instruct', 'deepseek-ai/deepseek-r1', 'qwen/qwen2.5-coder-32b-instruct'],
    priority: 24,
  },
  {
    id: 'huggingface',
    name: 'HuggingFace Router',
    tier: 'freemium',
    style: 'openai',
    baseUrl: 'https://router.huggingface.co/v1',
    getKey: 'https://huggingface.co/settings/tokens',
    note: 'Kredit inferensi gratis tiap bulan.',
    defaultModel: 'meta-llama/Llama-3.1-8B-Instruct',
    models: ['meta-llama/Llama-3.1-8B-Instruct', 'Qwen/Qwen2.5-7B-Instruct'],
    priority: 26,
  },
  {
    id: 'llm7',
    name: 'LLM7',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://api.llm7.io/v1',
    getKey: 'https://llm7.io',
    note: 'API gratis penuh, key instan tanpa kartu kredit.',
    defaultModel: 'gpt-4o-mini',
    models: ['gpt-4o-mini', 'gemini-2.0-flash', 'deepseek-chat'],
    priority: 28,
  },
  {
    id: 'pollinations',
    name: 'Pollinations',
    tier: 'free',
    style: 'openai',
    baseUrl: 'https://text.pollinations.ai/openai',
    getKey: null,
    keyless: true,
    note: 'Gratis TANPA API key — aktif otomatis sebagai jaring pengaman terakhir.',
    defaultModel: 'openai',
    models: ['openai', 'openai-fast', 'openai-large', 'mistral'],
    extraHeaders: { Referer: 'https://github.com/NetBypass/LoLLM' },
    priority: 30,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.deepseek.com/v1',
    getKey: 'https://platform.deepseek.com/api_keys',
    note: 'Murah, kuat (deepseek-chat / deepseek-reasoner).',
    defaultModel: 'deepseek-chat',
    models: ['deepseek-chat', 'deepseek-reasoner'],
    priority: 40,
  },
  {
    id: 'openai',
    name: 'OpenAI',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.openai.com/v1',
    getKey: 'https://platform.openai.com/api-keys',
    note: 'Resmi OpenAI.',
    defaultModel: 'gpt-4o-mini',
    models: ['gpt-4o-mini', 'gpt-4o', 'gpt-4.1', 'gpt-4.1-mini', 'o4-mini'],
    priority: 42,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    tier: 'paid',
    style: 'anthropic',
    baseUrl: 'https://api.anthropic.com',
    getKey: 'https://console.anthropic.com/settings/keys',
    note: 'Resmi Anthropic — request OpenAI ditranslasi otomatis ke Messages API.',
    defaultModel: 'claude-sonnet-4-20250514',
    models: ['claude-sonnet-4-20250514', 'claude-3-7-sonnet-latest', 'claude-3-5-haiku-latest'],
    priority: 44,
  },
  {
    id: 'xai',
    name: 'xAI (Grok)',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.x.ai/v1',
    getKey: 'https://console.x.ai',
    note: 'Grok.',
    defaultModel: 'grok-3',
    models: ['grok-3', 'grok-3-mini', 'grok-2-1212'],
    priority: 46,
  },
  {
    id: 'together',
    name: 'Together AI',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.together.xyz/v1',
    getKey: 'https://api.together.ai/settings/api-keys',
    note: 'Open-source models, kadang kredit trial.',
    defaultModel: 'meta-llama/Llama-3.3-70B-Instruct-Turbo',
    models: ['meta-llama/Llama-3.3-70B-Instruct-Turbo', 'meta-llama/Meta-Llama-3.1-8B-Instruct-Turbo', 'Qwen/Qwen2.5-Coder-32B-Instruct'],
    priority: 48,
  },
  {
    id: 'moonshot',
    name: 'Moonshot (Kimi)',
    tier: 'paid',
    style: 'openai',
    baseUrl: 'https://api.moonshot.ai/v1',
    getKey: 'https://platform.moonshot.cn/console/api-keys',
    note: 'Kimi.',
    defaultModel: 'moonshot-v1-8k',
    models: ['moonshot-v1-8k', 'moonshot-v1-32k', 'kimi-latest'],
    priority: 50,
  },
];

// Alias model populer → target "provider:model" (dicoba berurutan).
export const MODEL_ALIASES = {
  'gpt-4o-mini': ['github:openai/gpt-4o-mini', 'openai:gpt-4o-mini', 'llm7:gpt-4o-mini'],
  'gpt-4o': ['github:openai/gpt-4o', 'openai:gpt-4o'],
  'gpt-4.1': ['github:openai/gpt-4.1', 'openai:gpt-4.1'],
  'gpt-4.1-mini': ['github:openai/gpt-4.1-mini', 'openai:gpt-4.1-mini'],
  'o4-mini': ['github:openai/o4-mini', 'openai:o4-mini'],
  'llama-3.3-70b': ['groq:llama-3.3-70b-versatile', 'cerebras:llama-3.3-70b', 'together:meta-llama/Llama-3.3-70B-Instruct-Turbo'],
  'llama-3.3-70b-versatile': ['groq:llama-3.3-70b-versatile', 'cerebras:llama-3.3-70b'],
  'llama-3.1-8b': ['groq:llama-3.1-8b-instant', 'cerebras:llama3.1-8b'],
  'gemini-flash': ['google:gemini-2.5-flash'],
  'gemini-2.5-flash': ['google:gemini-2.5-flash'],
  'gemini-2.0-flash': ['google:gemini-2.0-flash', 'llm7:gemini-2.0-flash'],
  'glm-4.5-flash': ['zai:glm-4.5-flash'],
  'glm-4.7-flash': ['zai:glm-4.7-flash'],
  'mistral-small': ['mistral:mistral-small-latest'],
  'deepseek-chat': ['deepseek:deepseek-chat', 'llm7:deepseek-chat'],
  'deepseek-reasoner': ['deepseek:deepseek-reasoner'],
  'deepseek-r1': ['deepseek:deepseek-reasoner', 'github:deepseek/DeepSeek-R1', 'nvidia:deepseek-ai/deepseek-r1'],
};

// Provider yang langsung aktif tanpa perlu key.
export const DEFAULT_ON = ['pollinations'];

export function catalogById(id) {
  return CATALOG.find((p) => p.id === id) || null;
}
